version: '3.8'
name: dull-wars

services:

  app:
    build: ../
    command: >
      sh -c "python wsgi.py"
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
